<?php
namespace ADMIN\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * AlarmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmaRepository extends EntityRepository{
             
    
    public function getByFilter($filter){
    	
        
        $sSql = "SELECT a FROM ADMINAdminBundle:Alarma a LEFT JOIN a.alarid i LEFT JOIN a.estadoid e WHERE i IS NOT NULL ";
        
        if(!empty($filter["fDesde"])){
            $sSql .= " and a.fecha > to_date( '".$filter["fDesde"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter["fHasta"])){
            $sSql .= " and a.fecha <= to_date( '".$filter["fHasta"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter["pendiente"]) and $filter["pendiente"]){
            $sSql .= " and e.estadoid = 1";
        }
        
        if(!empty($filter['txtUsuario'])){
            if($filter['txtUsuario'] != ""){
                $sSql .= " and upper( a.usuario    ) like upper( '%".$filter['txtUsuario']   ."%' )";
            }
        }
        
        if(!empty($filter['txtDependencia'])){
        	if($filter['txtDependencia'] != ""){
        		$sSql .= " and upper(a.usuariodepen) like upper( '%".$filter['txtDependencia']   ."%' )";
        	}
        }
        
        if(!empty($filter['lstModo'])){
            if($filter['lstModo'] != ""){
                $sSql .= " and i.iaQueryMode = '".$filter['lstModo'] ."'";
            }
        }
        
        if($filter['lstTipoAlar'] != ""){
    	    switch($filter['lstTipoAlar']){
    	        case 2:
    	            $sSql .= " and a.altiid IN (2,3) ";
    	            break;
    	        case 4:
    	            $sSql .= " and a.altiid IN (4,5) ";
    	            break;
    	        case 7:
    	            $sSql .= " and a.altiid IN (7,8) ";
    	            break;
    	        case 10:
    	            $sSql .= " and a.altiid IN (10,11) ";
    	            break;
    	        case 13:
    	            $sSql .= " and a.altiid IN (13,14) ";
    	            break;
    	        default:    
    	            $sSql .= " and a.altiid = ".$filter['lstTipoAlar'] ." ";
    	    }
    	}
        
        
        $sSql .= " ORDER BY a.alarid DESC";
        
        $query = $this->getEntityManager()->createQuery( $sSql  );
        
        return $query;
        
    }
    
    
    public function getTotalesXTipo($filter){
        $sSql = "SELECT t.nombre AS tipo, t.textcolor, t.backcolor, SUM(1) AS cant FROM ADMINAdminBundle:Alarma a LEFT JOIN a.altiid t WHERE 1=1 ";
        
        if(!empty($filter["fDesde"])){
            $sSql .= " and a.fecha > to_date( '".$filter["fDesde"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter["fHasta"])){
            $sSql .= " and a.fecha <= to_date( '".$filter["fHasta"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter['txtDependencia'])){
            if($filter['txtDependencia'] != ""){
                $sSql .= " and upper(a.usuariodepen) like upper( '%".$filter['txtDependencia']   ."%' )";
            }
        }
        
        if(is_array($filter['lstTipoAlar']) && count($filter['lstTipoAlar'])>0){
            
            $sSql .= " and ( ";
            
            foreach($filter['lstTipoAlar'] as $tipo){
                switch($tipo){
                    case 2:
                        $sSql .= "a.altiid IN (2,3) ";
                        break;
                    case 4:
                        $sSql .= "a.altiid IN (4,5) ";
                        break;
                    case 7:
                        $sSql .= "a.altiid IN (7,8) ";
                        break;
                    case 10:
                        $sSql .= "a.altiid IN (10,11) ";
                        break;
                    case 13:
                        $sSql .= "a.altiid IN (13,14) ";
                        break;
                    default:
                        $sSql .= "a.altiid = ".$tipo." ";
                }
                
                $sSql .= " or ";
                
            }
            
            $sSql = substr($sSql,0,-4);
            
            $sSql .= " ) ";
        }
        
        $sSql .= " GROUP BY t.nombre, t.textcolor, t.backcolor";
        
        $query = $this->getEntityManager()->createQuery( $sSql  );
        
        return $query->getResult();
        
    }

    
}
