<?php
namespace ADMIN\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * AlarmatipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmatipoRepository extends EntityRepository{
             
    
    public function getAlarmasTipos(){
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $query = $qb->select('a')
                    ->from('ADMIN\AdminBundle\Entity\Alarmatipo','a')
                    ->where('a.altiid NOT IN (3,5,8,11,14)')
                    ->orderBy('a.altiid', 'ASC');
        
        return $query->getQuery()->getResult();
    }
    
    
}
