cnrtpersona:
    path: /
    defaults:    { _controller: "ADMINAdminBundle:CnrtPersona:index" }
admin_cnrtpersona:
    path: /{page}
    defaults:    { _controller: "ADMINAdminBundle:CnrtPersona:index",page:1 }
cnrt_consultarPersonasCnrtId:
    path: /{id}/consultarPersonasCnrtId
    defaults:    { _controller: "ADMINAdminBundle:CnrtPersona:consultarPersonasCnrtId" }
cnrt_verificarDatosPasajero:
    path: /{id}/verificarDatosPasajero
    defaults:    { _controller: "ADMINAdminBundle:CnrtPersona:verificarDatosPasajero" }    
cnrt_reprocesarInterpol:
    path: /{id}/reprocesarInterpol
    defaults:    { _controller: "ADMINAdminBundle:CnrtPersona:reprocesarInterpol" }
cnrt_auditoria:
    path:     /{id}/auditoria
    defaults: { _controller: "ADMINAdminBundle:CnrtPersona:auditoria" }
cnrt_audito_reporte:
    path:     /{id}/reporteAuditoria
    defaults: { _controller: "ADMINAdminBundle:CnrtPersona:auditarReportePDF" }