lotedocumento:
    path:     /
    defaults: { _controller: "ADMINAdminBundle:LoteDocumento:index" }
lotedocumento_show:
    path:     /lotedocumentoshow/{page}
    defaults: { _controller: "ADMINAdminBundle:LoteDocumento:show",page:1 }
lotedocumento_consulta:
    path:     /consulta
    defaults: { _controller: "ADMINAdminBundle:LoteDocumento:consulta" }
lotedocumento_procesarCurlDoc:
    path: /procesarCurlDoc
    defaults:   { _controller: "ADMINAdminBundle:LoteDocumento:procesarCurlDoc" }
lotedocumento_actualizarMensaje:
    path: /actualizarMensaje
    defaults:   { _controller: "ADMINAdminBundle:LoteDocumento:actualizarMensaje" } 
carga_masiva_progreso:
    path: /cargaMasivaProgreso
    defaults:   { _controller: "ADMINAdminBundle:LoteDocumento:cargaMasivaProgreso" } 
lotedocumento_ejecutarStartInit:
    path: /ejecutarStartInit
    defaults:   { _controller: "ADMINAdminBundle:LoteDocumento:ejecutarStartInit" } 
lotedocumento_ejecutarFinalizeInit:
    path: /ejecutarFinalizeInit
    defaults:   { _controller: "ADMINAdminBundle:LoteDocumento:ejecutarFinalizeInit" }
    