admin_mapa:
    path:     /
    defaults: { _controller: "ADMINAdminBundle:Mapa:index" }

admin_mapa_show:
    path:     /{id}/show
    defaults: { _controller: "ADMINAdminBundle:Mapa:show" }

admin_mapa_new:
    path:     /new
    defaults: { _controller: "ADMINAdminBundle:Mapa:new" }

admin_mapa_create:
    path:     /create
    defaults: { _controller: "ADMINAdminBundle:Mapa:create" }
    requirements: { _method: post }

admin_mapa_edit:
    path:     /{id}/edit
    defaults: { _controller: "ADMINAdminBundle:Mapa:edit" }

admin_mapa_update:
    path:     /{id}/update
    defaults: { _controller: "ADMINAdminBundle:Mapa:update" }
    requirements: { _method: post|put }

admin_mapa_delete:
    path:     /{id}/delete
    defaults: { _controller: "ADMINAdminBundle:Mapa:delete" }
    requirements: { _method: post|delete }

admin_mapa_mapaDependencia:
    path:     /{id}/mapaDependencia
    defaults: { _controller: "ADMINAdminBundle:Mapa:mapaDependencia" }
