admin_proceso:
    path:     /
    defaults: { _controller: "ADMINAdminBundle:Proceso:index" }

admin_proceso_show:
    path:     /{id}/show
    defaults: { _controller: "ADMINAdminBundle:Proceso:show" }
    
admin_proceso_test:
    path:     /test
    defaults: { _controller: "ADMINAdminBundle:Proceso:test" }

admin_proceso_parametros:
    path:     /parametros
    defaults: { _controller: "ADMINAdminBundle:Proceso:parametros" }

admin_proceso_parametros_update:
    path: /updateParametro
    defaults:    { _controller: "ADMINAdminBundle:Proceso:updateParametro" }
