admin_Tipodelito:
    path:     /
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:index" }

admin_Tipodelito_show:
    path:     /{id}/show
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:show" }

admin_Tipodelito_new:
    path:     /new
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:new" }

admin_Tipodelito_create:
    path:     /create
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:create" }
    requirements: { _method: post }

admin_Tipodelito_edit:
    path:     /{id}/edit
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:edit" }

admin_Tipodelito_update:
    path:     /{id}/update
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:update" }
    requirements: { _method: post|put }

admin_Tipodelito_delete:
    path:     /{id}/delete
    defaults: { _controller: "ADMINAdminBundle:Tipodelito:delete" }
    requirements: { _method: post|delete }