<?php

namespace SEGURIDAD\SeguridadBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * DependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRepository extends EntityRepository{
    
    
    public function getByFilter($filter){
        
        $sSql = "SELECT d FROM SEGURIDADSeguridadBundle:Dependencia d WHERE 1=1 ";
        
        if(!empty($filter['txtNombre'])){
            if($filter['txtNombre'] != ""){
                $sSql .= " and upper(d.nombre) like upper( '%".$filter['txtNombre']   ."%' )";
            }
        }
        $sSql .= " ORDER BY d.id DESC";
        
        $query = $this->getEntityManager()->createQuery( $sSql  );
        
        return $query;
        
    }
    
    public function autocompletar($filter){
        
        $sSql = "SELECT d.id as id, d.nombre AS nombre FROM SEGURIDADSeguridadBundle:Dependencia d WHERE d.borrado = 0 ";
        
        if(!empty($filter['term'])){
			$sSql .= " and upper( d.nombre ) like upper( '%".$filter['term'] ."%') or d.codigo like upper( '%".$filter['term'] ."%')";
        }

        $sSql .= " ORDER BY d.nombre ASC";

        $query = $this->getEntityManager()->createQuery( $sSql  );
        $oRes = $query->getResult();
        
        return $oRes;
        
    }
    
    
    
}
