<?php
namespace SEGURIDAD\SeguridadBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository{
             
    
    public function getByFilter($filter){
    	
        
        $sSql = "SELECT u, d FROM SEGURIDADSeguridadBundle:Usuario u LEFT OUTER JOIN u.depenid d";
        
        if(!empty($filter['optPerfiles']) && is_array($filter['optPerfiles'])){
            $sSql .= " LEFT OUTER JOIN u.perfilid p";
        }
        
        $sSql .= " WHERE 1=1 ";
        
        if(!empty($filter["fDesde"])){
            $sSql .= " and u.fechaalta > to_date( '".$filter["fDesde"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter["fHasta"])){
            $sSql .= " and u.fechaalta <= to_date( '".$filter["fHasta"]."', 'DD/MM/YYYY HH24:MI:SS' )";
        }
        
        if(!empty($filter['txtUsuario'])){
            if($filter['txtUsuario'] != ""){
                $sSql .= " and upper(u.usuario) like upper( '%".$filter['txtUsuario']   ."%' )";
            }
        }
        
        if(!empty($filter['txtNombre'])){
            if($filter['txtNombre'] != ""){
                $sSql .= " and upper(u.nombre) like upper( '%".$filter['txtNombre']   ."%' )";
            }
        }
        
        if(!empty($filter['txtApellido'])){
            if($filter['txtApellido'] != ""){
                $sSql .= " and upper(u.apellido) like upper( '%".$filter['txtApellido']   ."%' )";
            }
        }
        
        if(!empty($filter['txtDependencia'])){
        	if($filter['txtDependencia'] != ""){
        		$sSql .= " and upper(d.nombre) like upper( '%".$filter['txtDependencia']   ."%' )";
        	}
        }
        
        if(!empty($filter['optEstado']) && $filter['optEstado']!=''){
            
            switch($filter['optEstado']){
                case 'A': 
                    $sSql .= " and u.activo = 1 and u.borrado = 0";
                    break;
                case 'I':
                    $sSql .= " and u.activo = 0 and u.borrado = 0";
                    break;
                case 'B':
                    $sSql .= " and u.borrado = 1";
                    break;
            }
        }
        
        
        if(!empty($filter['optPerfiles']) && is_array($filter['optPerfiles'])){
            
            $sSql .= " and p.id in (";
            
            $idPerfiles = '';
            
            foreach($filter['optPerfiles'] as $perfilId){
                $idPerfiles .= $perfilId.",";
            }
            
            $sSql .= substr($idPerfiles,0,-1).")";
        }
        
        $sSql .= " ORDER BY u.id DESC";
        
        $query = $this->getEntityManager()->createQuery( $sSql  );
        
        return $query->getResult();
        
    }
    
    
    
}
