<?php

namespace GESTION\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultaLoteDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaLoteDetalleRepository extends EntityRepository
{
	
	public function traerDetalles($id){
		
		$query = $this->getEntityManager()->createQuery(
				"SELECT e
			      FROM GESTIONGestionBundle:ConsultaLoteDetalle e
			      WHERE e.consultaLoteId = :id AND e.resultCode IS NULL OR e.resultCode = :error 
				  ORDER BY e.fecMod DESC"
				)->setParameter(':id',$id)->setParameter(':error','ERROR');
				
		return $query->getResult();
	}
	
    public function resultadosParciales($id){
        
        $query = $this->getEntityManager()->createQuery(
            "SELECT e
		      FROM GESTIONGestionBundle:ConsultaLoteDetalle e
		      WHERE e.consultaLoteId = :id AND e.leido IS NULL AND e.resultCode IS NOT NULL
		      ORDER BY e.fecMod DESC"
            )->setParameter(':id',$id);
            
            return $query->getResult();
    }
    
    public function iniciarVariablesError($id){
    	$query = $this->getEntityManager()->createQuery(
    			"UPDATE GESTIONGestionBundle:ConsultaLoteDetalle e
			     SET e.resultCode=null, e.respuesta = null, e.respuestaDetails=null, e.leido = null
		     	 WHERE e.consultaLoteId = :id AND e.resultCode = :error"
    			)->setParameter(':id',$id)->setParameter(':error','ERROR');
    			
    	return $query->execute();
    }
}
